DROP TABLE PRODUCT_PROPERTY;
DROP TABLE PRODUCT;
DROP TABLE PROPERTY;
CREATE TABLE PRODUCT(
	id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    sku VARCHAR(12) NOT NULL,
    type VARCHAR(50) NOT NULL,
    price DOUBLE,
    UNIQUE(sku)
);

CREATE TABLE PROPERTY(
	id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    UNIQUE (name)
);

CREATE TABLE PRODUCT_PROPERTY(
    product_id INT,
    property_id INT,
    value VARCHAR(100) NOT NULL,
    PRIMARY KEY (product_id, property_id),
    FOREIGN KEY (product_id) REFERENCES PRODUCT(id) ON DELETE CASCADE,
    FOREIGN KEY (property_id) REFERENCES PROPERTY(id) ON DELETE CASCADE
);